# Generated by Django 3.2.16 on 2023-01-20 03:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inviter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitee_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
