# Generated by Django 3.2.16 on 2023-01-20 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skye', '0003_gift_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='reason',
            field=models.CharField(choices=[('accepted_invitation', 'Accepted Invitation'), ('successful_invitation', 'Successful Invitation'), ('invitee_redeemed', 'Invitee Redeemed')], default='', max_length=50),
        ),
    ]
