# Generated by Django 3.2.16 on 2023-01-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skye', '0004_alter_gift_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completion',
            name='model',
            field=models.CharField(max_length=35),
        ),
    ]
